// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/github-vuln-watcher/pkg/filter"
)

type CursorReader struct {
	LastEmittedTaskIdentifierStub        func(string) string
	lastEmittedTaskIdentifierMutex       sync.RWMutex
	lastEmittedTaskIdentifierArgsForCall []struct {
		arg1 string
	}
	lastEmittedTaskIdentifierReturns struct {
		result1 string
	}
	lastEmittedTaskIdentifierReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CursorReader) LastEmittedTaskIdentifier(arg1 string) string {
	fake.lastEmittedTaskIdentifierMutex.Lock()
	ret, specificReturn := fake.lastEmittedTaskIdentifierReturnsOnCall[len(fake.lastEmittedTaskIdentifierArgsForCall)]
	fake.lastEmittedTaskIdentifierArgsForCall = append(fake.lastEmittedTaskIdentifierArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LastEmittedTaskIdentifierStub
	fakeReturns := fake.lastEmittedTaskIdentifierReturns
	fake.recordInvocation("LastEmittedTaskIdentifier", []interface{}{arg1})
	fake.lastEmittedTaskIdentifierMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CursorReader) LastEmittedTaskIdentifierCallCount() int {
	fake.lastEmittedTaskIdentifierMutex.RLock()
	defer fake.lastEmittedTaskIdentifierMutex.RUnlock()
	return len(fake.lastEmittedTaskIdentifierArgsForCall)
}

func (fake *CursorReader) LastEmittedTaskIdentifierCalls(stub func(string) string) {
	fake.lastEmittedTaskIdentifierMutex.Lock()
	defer fake.lastEmittedTaskIdentifierMutex.Unlock()
	fake.LastEmittedTaskIdentifierStub = stub
}

func (fake *CursorReader) LastEmittedTaskIdentifierArgsForCall(i int) string {
	fake.lastEmittedTaskIdentifierMutex.RLock()
	defer fake.lastEmittedTaskIdentifierMutex.RUnlock()
	argsForCall := fake.lastEmittedTaskIdentifierArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CursorReader) LastEmittedTaskIdentifierReturns(result1 string) {
	fake.lastEmittedTaskIdentifierMutex.Lock()
	defer fake.lastEmittedTaskIdentifierMutex.Unlock()
	fake.LastEmittedTaskIdentifierStub = nil
	fake.lastEmittedTaskIdentifierReturns = struct {
		result1 string
	}{result1}
}

func (fake *CursorReader) LastEmittedTaskIdentifierReturnsOnCall(i int, result1 string) {
	fake.lastEmittedTaskIdentifierMutex.Lock()
	defer fake.lastEmittedTaskIdentifierMutex.Unlock()
	fake.LastEmittedTaskIdentifierStub = nil
	if fake.lastEmittedTaskIdentifierReturnsOnCall == nil {
		fake.lastEmittedTaskIdentifierReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.lastEmittedTaskIdentifierReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *CursorReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CursorReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ filter.CursorReader = new(CursorReader)
