// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/github-vuln-watcher/pkg"
)

type CycleGate struct {
	ReleaseStub        func()
	releaseMutex       sync.RWMutex
	releaseArgsForCall []struct {
	}
	TryAcquireStub        func() bool
	tryAcquireMutex       sync.RWMutex
	tryAcquireArgsForCall []struct {
	}
	tryAcquireReturns struct {
		result1 bool
	}
	tryAcquireReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CycleGate) Release() {
	fake.releaseMutex.Lock()
	fake.releaseArgsForCall = append(fake.releaseArgsForCall, struct {
	}{})
	stub := fake.ReleaseStub
	fake.recordInvocation("Release", []interface{}{})
	fake.releaseMutex.Unlock()
	if stub != nil {
		fake.ReleaseStub()
	}
}

func (fake *CycleGate) ReleaseCallCount() int {
	fake.releaseMutex.RLock()
	defer fake.releaseMutex.RUnlock()
	return len(fake.releaseArgsForCall)
}

func (fake *CycleGate) ReleaseCalls(stub func()) {
	fake.releaseMutex.Lock()
	defer fake.releaseMutex.Unlock()
	fake.ReleaseStub = stub
}

func (fake *CycleGate) TryAcquire() bool {
	fake.tryAcquireMutex.Lock()
	ret, specificReturn := fake.tryAcquireReturnsOnCall[len(fake.tryAcquireArgsForCall)]
	fake.tryAcquireArgsForCall = append(fake.tryAcquireArgsForCall, struct {
	}{})
	stub := fake.TryAcquireStub
	fakeReturns := fake.tryAcquireReturns
	fake.recordInvocation("TryAcquire", []interface{}{})
	fake.tryAcquireMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CycleGate) TryAcquireCallCount() int {
	fake.tryAcquireMutex.RLock()
	defer fake.tryAcquireMutex.RUnlock()
	return len(fake.tryAcquireArgsForCall)
}

func (fake *CycleGate) TryAcquireCalls(stub func() bool) {
	fake.tryAcquireMutex.Lock()
	defer fake.tryAcquireMutex.Unlock()
	fake.TryAcquireStub = stub
}

func (fake *CycleGate) TryAcquireReturns(result1 bool) {
	fake.tryAcquireMutex.Lock()
	defer fake.tryAcquireMutex.Unlock()
	fake.TryAcquireStub = nil
	fake.tryAcquireReturns = struct {
		result1 bool
	}{result1}
}

func (fake *CycleGate) TryAcquireReturnsOnCall(i int, result1 bool) {
	fake.tryAcquireMutex.Lock()
	defer fake.tryAcquireMutex.Unlock()
	fake.TryAcquireStub = nil
	if fake.tryAcquireReturnsOnCall == nil {
		fake.tryAcquireReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.tryAcquireReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *CycleGate) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CycleGate) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.CycleGate = new(CycleGate)
